import React, { useState, useEffect } from 'react';

//svg
import { ReactComponent as AllTracks } from '../../assets/AllTrack.svg';

//componenets
import Tracks from './Tracks';

export default function DropDown() {
  const [first, setfirst] = useState('alltracks');

  const tacks = {
    tracks: [
      {
        slug: 'bash',
        title: 'Bash',
        course: false,
        num_concepts: 0,
        num_exercises: 89,
        web_url: 'https://exercism.org/tracks/bash',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/bash.svg',
        tags: ['Scripts', 'Procedural', 'Interpreted', 'Weak', 'Linux', 'Mac OSX', 'Windows'],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/bash',
          exercises: 'https://exercism.org/tracks/bash/exercises',
          concepts: 'https://exercism.org/tracks/bash/concepts',
        },
      },
      {
        slug: 'c',
        title: 'C',
        course: false,
        num_concepts: 0,
        num_exercises: 71,
        web_url: 'https://exercism.org/tracks/c',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/c.svg',
        tags: [
          'Compiled',
          'Procedural',
          'Static',
          'Android',
          'iOS',
          'Linux',
          'Mac OSX',
          'Windows',
          'Language-specific runtime',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Financial systems',
          'Frontends',
          'Games',
          'GUIs',
          'Mobile',
          'Robotics',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/c',
          exercises: 'https://exercism.org/tracks/c/exercises',
          concepts: 'https://exercism.org/tracks/c/concepts',
        },
      },
      {
        slug: 'csharp',
        title: 'C#',
        course: true,
        num_concepts: 62,
        num_exercises: 164,
        web_url: 'https://exercism.org/tracks/csharp',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/csharp.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Common Language Runtime (.NET)',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Games',
          'GUIs',
          'Mobile',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/csharp',
          exercises: 'https://exercism.org/tracks/csharp/exercises',
          concepts: 'https://exercism.org/tracks/csharp/concepts',
        },
      },
      {
        slug: 'cpp',
        title: 'C++',
        course: false,
        num_concepts: 0,
        num_exercises: 55,
        web_url: 'https://exercism.org/tracks/cpp',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/cpp.svg',
        tags: [
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Android',
          'iOS',
          'Linux',
          'Mac OSX',
          'Windows',
          'Standalone executable',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Financial systems',
          'Games',
          'GUIs',
          'Mobile',
          'Robotics',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/cpp',
          exercises: 'https://exercism.org/tracks/cpp/exercises',
          concepts: 'https://exercism.org/tracks/cpp/concepts',
        },
      },
      {
        slug: 'cfml',
        title: 'CFML',
        course: false,
        num_concepts: 0,
        num_exercises: 28,
        web_url: 'https://exercism.org/tracks/cfml',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/cfml.svg',
        tags: [
          'Declarative',
          'Dynamic',
          'Interpreted',
          'Web Browser',
          'Language-specific runtime',
          'Backends',
          'Frontends',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/cfml',
          exercises: 'https://exercism.org/tracks/cfml/exercises',
          concepts: 'https://exercism.org/tracks/cfml/concepts',
        },
      },
      {
        slug: 'clojure',
        title: 'Clojure',
        course: true,
        num_concepts: 9,
        num_exercises: 84,
        web_url: 'https://exercism.org/tracks/clojure',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/clojure.svg',
        tags: [
          'Declarative',
          'Functional',
          'Dynamic',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'JVM (Java)',
          'Artificial Intelligence',
          'Backends',
          'Cross-platform development',
          'Financial systems',
          'Frontends',
          'Games',
          'GUIs',
          'Robotics',
          'Scientific calculations',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/clojure',
          exercises: 'https://exercism.org/tracks/clojure/exercises',
          concepts: 'https://exercism.org/tracks/clojure/concepts',
        },
      },
      {
        slug: 'clojurescript',
        title: 'ClojureScript',
        course: false,
        num_concepts: 0,
        num_exercises: 26,
        web_url: 'https://exercism.org/tracks/clojurescript',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/clojurescript.svg',
        tags: [
          'Declarative',
          'Functional',
          'Dynamic',
          'Compiled',
          'Web Browser',
          'Frontends',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/clojurescript',
          exercises: 'https://exercism.org/tracks/clojurescript/exercises',
          concepts: 'https://exercism.org/tracks/clojurescript/concepts',
        },
      },
      {
        slug: 'coffeescript',
        title: 'CoffeeScript',
        course: false,
        num_concepts: 0,
        num_exercises: 21,
        web_url: 'https://exercism.org/tracks/coffeescript',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/coffeescript.svg',
        tags: [
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Dynamic',
          'Weak',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Games',
          'GUIs',
          'Mobile',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/coffeescript',
          exercises: 'https://exercism.org/tracks/coffeescript/exercises',
          concepts: 'https://exercism.org/tracks/coffeescript/concepts',
        },
      },
      {
        slug: 'common-lisp',
        title: 'Common Lisp',
        course: true,
        num_concepts: 27,
        num_exercises: 55,
        web_url: 'https://exercism.org/tracks/common-lisp',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/common-lisp.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Procedural',
          'Dynamic',
          'Strong',
          'Compiled',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Artificial Intelligence',
          'Backends',
          'Games',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/common-lisp',
          exercises: 'https://exercism.org/tracks/common-lisp/exercises',
          concepts: 'https://exercism.org/tracks/common-lisp/concepts',
        },
      },
      {
        slug: 'crystal',
        title: 'Crystal',
        course: false,
        num_concepts: 0,
        num_exercises: 50,
        web_url: 'https://exercism.org/tracks/crystal',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/crystal.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Procedural',
          'Static',
          'Compiled',
          'Mac OSX',
          'Linux',
          'Standalone executable',
          'Backends',
          'Cross-platform development',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/crystal',
          exercises: 'https://exercism.org/tracks/crystal/exercises',
          concepts: 'https://exercism.org/tracks/crystal/concepts',
        },
      },
      {
        slug: 'd',
        title: 'D',
        course: false,
        num_concepts: 0,
        num_exercises: 34,
        web_url: 'https://exercism.org/tracks/d',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/d.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Financial systems',
          'Games',
          'GUIs',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/d',
          exercises: 'https://exercism.org/tracks/d/exercises',
          concepts: 'https://exercism.org/tracks/d/concepts',
        },
      },
      {
        slug: 'dart',
        title: 'Dart',
        course: false,
        num_concepts: 0,
        num_exercises: 37,
        web_url: 'https://exercism.org/tracks/dart',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/dart.svg',
        tags: [
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Cross-platform development',
          'Games',
          'GUIs',
          'Mobile',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/dart',
          exercises: 'https://exercism.org/tracks/dart/exercises',
          concepts: 'https://exercism.org/tracks/dart/concepts',
        },
      },
      {
        slug: 'delphi',
        title: 'Delphi Pascal',
        course: false,
        num_concepts: 0,
        num_exercises: 76,
        web_url: 'https://exercism.org/tracks/delphi',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/delphi.svg',
        tags: [
          'Declarative',
          'Imperative',
          'Object-oriented',
          'Procedural',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Standalone executable',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Games',
          'GUIs',
          'Web development',
          'Financial systems',
          'Mobile',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/delphi',
          exercises: 'https://exercism.org/tracks/delphi/exercises',
          concepts: 'https://exercism.org/tracks/delphi/concepts',
        },
      },
      {
        slug: 'elixir',
        title: 'Elixir',
        course: true,
        num_concepts: 54,
        num_exercises: 152,
        web_url: 'https://exercism.org/tracks/elixir',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/elixir.svg',
        tags: [
          'Functional',
          'Dynamic',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'BEAM (Erlang)',
          'Backends',
          'Embedded systems',
          'Financial systems',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/elixir',
          exercises: 'https://exercism.org/tracks/elixir/exercises',
          concepts: 'https://exercism.org/tracks/elixir/concepts',
        },
      },
      {
        slug: 'elm',
        title: 'Elm',
        course: true,
        num_concepts: 11,
        num_exercises: 58,
        web_url: 'https://exercism.org/tracks/elm',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/elm.svg',
        tags: [
          'Functional',
          'Static',
          'Strong',
          'Compiled',
          'Web Browser',
          'Frontends',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/elm',
          exercises: 'https://exercism.org/tracks/elm/exercises',
          concepts: 'https://exercism.org/tracks/elm/concepts',
        },
      },
      {
        slug: 'emacs-lisp',
        title: 'Emacs Lisp',
        course: false,
        num_concepts: 0,
        num_exercises: 28,
        web_url: 'https://exercism.org/tracks/emacs-lisp',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/emacs-lisp.svg',
        tags: [
          'Functional',
          'Dynamic',
          'Strong',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/emacs-lisp',
          exercises: 'https://exercism.org/tracks/emacs-lisp/exercises',
          concepts: 'https://exercism.org/tracks/emacs-lisp/concepts',
        },
      },
      {
        slug: 'erlang',
        title: 'Erlang',
        course: false,
        num_concepts: 0,
        num_exercises: 77,
        web_url: 'https://exercism.org/tracks/erlang',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/erlang.svg',
        tags: [
          'Functional',
          'Dynamic',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'BEAM (Erlang)',
          'Backends',
          'Embedded systems',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/erlang',
          exercises: 'https://exercism.org/tracks/erlang/exercises',
          concepts: 'https://exercism.org/tracks/erlang/concepts',
        },
      },
      {
        slug: 'fsharp',
        title: 'F#',
        course: true,
        num_concepts: 14,
        num_exercises: 132,
        web_url: 'https://exercism.org/tracks/fsharp',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/fsharp.svg',
        tags: [
          'Functional',
          'Declarative',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Common Language Runtime (.NET)',
          'Artificial Intelligence',
          'Backends',
          'Cross-platform development',
          'Financial systems',
          'Scientific calculations',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/fsharp',
          exercises: 'https://exercism.org/tracks/fsharp/exercises',
          concepts: 'https://exercism.org/tracks/fsharp/concepts',
        },
      },
      {
        slug: 'fortran',
        title: 'Fortran',
        course: false,
        num_concepts: 0,
        num_exercises: 22,
        web_url: 'https://exercism.org/tracks/fortran',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/fortran.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/fortran',
          exercises: 'https://exercism.org/tracks/fortran/exercises',
          concepts: 'https://exercism.org/tracks/fortran/concepts',
        },
      },
      {
        slug: 'go',
        title: 'Go',
        course: true,
        num_concepts: 26,
        num_exercises: 130,
        web_url: 'https://exercism.org/tracks/go',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/go.svg',
        tags: [
          'Procedural',
          'Imperative',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Standalone executable',
          'Backends',
          'Cross-platform development',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/go',
          exercises: 'https://exercism.org/tracks/go/exercises',
          concepts: 'https://exercism.org/tracks/go/concepts',
        },
      },
      {
        slug: 'groovy',
        title: 'Groovy',
        course: false,
        num_concepts: 0,
        num_exercises: 55,
        web_url: 'https://exercism.org/tracks/groovy',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/groovy.svg',
        tags: [
          'Compiled',
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Windows',
          'Linux',
          'Mac OSX',
          'Android',
          'JVM (Java)',
          'Static',
          'Dynamic',
          'Backends',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/groovy',
          exercises: 'https://exercism.org/tracks/groovy/exercises',
          concepts: 'https://exercism.org/tracks/groovy/concepts',
        },
      },
      {
        slug: 'haskell',
        title: 'Haskell',
        course: false,
        num_concepts: 1,
        num_exercises: 97,
        web_url: 'https://exercism.org/tracks/haskell',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/haskell.svg',
        tags: ['Functional'],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/haskell',
          exercises: 'https://exercism.org/tracks/haskell/exercises',
          concepts: 'https://exercism.org/tracks/haskell/concepts',
        },
      },
      {
        slug: 'java',
        title: 'Java',
        course: true,
        num_concepts: 17,
        num_exercises: 129,
        web_url: 'https://exercism.org/tracks/java',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/java.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Android',
          'JVM (Java)',
          'Backends',
          'Cross-platform development',
          'Mobile',
          'Artificial Intelligence',
          'Games',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/java',
          exercises: 'https://exercism.org/tracks/java/exercises',
          concepts: 'https://exercism.org/tracks/java/concepts',
        },
      },
      {
        slug: 'javascript',
        title: 'JavaScript',
        course: true,
        num_concepts: 31,
        num_exercises: 139,
        web_url: 'https://exercism.org/tracks/javascript',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/javascript.svg',
        tags: [
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Dynamic',
          'Weak',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Artificial Intelligence',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Games',
          'GUIs',
          'Mobile',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/javascript',
          exercises: 'https://exercism.org/tracks/javascript/exercises',
          concepts: 'https://exercism.org/tracks/javascript/concepts',
        },
      },
      {
        slug: 'julia',
        title: 'Julia',
        course: false,
        num_concepts: 3,
        num_exercises: 51,
        web_url: 'https://exercism.org/tracks/julia',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/julia.svg',
        tags: [
          'Compiled',
          'Dynamic',
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Procedural',
          'Windows',
          'Mac OSX',
          'Linux',
          'Artificial Intelligence',
          'Cross-platform development',
          'Financial systems',
          'Robotics',
          'Scientific calculations',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/julia',
          exercises: 'https://exercism.org/tracks/julia/exercises',
          concepts: 'https://exercism.org/tracks/julia/concepts',
        },
      },
      {
        slug: 'kotlin',
        title: 'Kotlin',
        course: false,
        num_concepts: 0,
        num_exercises: 85,
        web_url: 'https://exercism.org/tracks/kotlin',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/kotlin.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Android',
          'Web Browser',
          'JVM (Java)',
          'Backends',
          'Cross-platform development',
          'Mobile',
          'Games',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/kotlin',
          exercises: 'https://exercism.org/tracks/kotlin/exercises',
          concepts: 'https://exercism.org/tracks/kotlin/concepts',
        },
      },
      {
        slug: 'lfe',
        title: 'LFE',
        course: false,
        num_concepts: 0,
        num_exercises: 31,
        web_url: 'https://exercism.org/tracks/lfe',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/lfe.svg',
        tags: [
          'Functional',
          'Dynamic',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'BEAM (Erlang)',
          'Backends',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/lfe',
          exercises: 'https://exercism.org/tracks/lfe/exercises',
          concepts: 'https://exercism.org/tracks/lfe/concepts',
        },
      },
      {
        slug: 'lua',
        title: 'Lua',
        course: false,
        num_concepts: 0,
        num_exercises: 82,
        web_url: 'https://exercism.org/tracks/lua',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/lua.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Object-oriented',
          'Dynamic',
          'Strong',
          'Interpreted',
          'Linux',
          'Mac OSX',
          'Windows',
          'Language-specific runtime',
          'Embedded systems',
          'Games',
          'Scripts',
          'Backends',
          'Cross-platform development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/lua',
          exercises: 'https://exercism.org/tracks/lua/exercises',
          concepts: 'https://exercism.org/tracks/lua/concepts',
        },
      },
      {
        slug: 'mips',
        title: 'MIPS Assembly',
        course: false,
        num_concepts: 0,
        num_exercises: 15,
        web_url: 'https://exercism.org/tracks/mips',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/mips.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Static',
          'Weak',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Standalone executable',
          'Embedded systems',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/mips',
          exercises: 'https://exercism.org/tracks/mips/exercises',
          concepts: 'https://exercism.org/tracks/mips/concepts',
        },
      },
      {
        slug: 'nim',
        title: 'Nim',
        course: false,
        num_concepts: 0,
        num_exercises: 67,
        web_url: 'https://exercism.org/tracks/nim',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/nim.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Web Browser',
          'Standalone executable',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Frontends',
          'Games',
          'Scientific calculations',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/nim',
          exercises: 'https://exercism.org/tracks/nim/exercises',
          concepts: 'https://exercism.org/tracks/nim/concepts',
        },
      },
      {
        slug: 'objective-c',
        title: 'Objective-C',
        course: false,
        num_concepts: 0,
        num_exercises: 51,
        web_url: 'https://exercism.org/tracks/objective-c',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/objective-c.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Object-oriented',
          'Static',
          'Dynamic',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Language-specific runtime',
          'Backends',
          'Frontends',
          'Mobile',
          'GUIs',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/objective-c',
          exercises: 'https://exercism.org/tracks/objective-c/exercises',
          concepts: 'https://exercism.org/tracks/objective-c/concepts',
        },
      },
      {
        slug: 'ocaml',
        title: 'OCaml',
        course: false,
        num_concepts: 0,
        num_exercises: 44,
        web_url: 'https://exercism.org/tracks/ocaml',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/ocaml.svg',
        tags: [
          'Functional',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Financial systems',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/ocaml',
          exercises: 'https://exercism.org/tracks/ocaml/exercises',
          concepts: 'https://exercism.org/tracks/ocaml/concepts',
        },
      },
      {
        slug: 'perl5',
        title: 'Perl 5',
        course: false,
        num_concepts: 0,
        num_exercises: 62,
        web_url: 'https://exercism.org/tracks/perl5',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/perl5.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Dynamic',
          'Weak',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Standalone executable',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/perl5',
          exercises: 'https://exercism.org/tracks/perl5/exercises',
          concepts: 'https://exercism.org/tracks/perl5/concepts',
        },
      },
      {
        slug: 'pharo-smalltalk',
        title: 'Pharo',
        course: false,
        num_concepts: 0,
        num_exercises: 42,
        web_url: 'https://exercism.org/tracks/pharo-smalltalk',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/pharo-smalltalk.svg',
        tags: [
          'Object-oriented',
          'Dynamic',
          'Strong',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/pharo-smalltalk',
          exercises: 'https://exercism.org/tracks/pharo-smalltalk/exercises',
          concepts: 'https://exercism.org/tracks/pharo-smalltalk/concepts',
        },
      },
      {
        slug: 'php',
        title: 'PHP',
        course: false,
        num_concepts: 0,
        num_exercises: 79,
        web_url: 'https://exercism.org/tracks/php',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/php.svg',
        tags: [
          'Imperative',
          'Object-oriented',
          'Procedural',
          'Dynamic',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/php',
          exercises: 'https://exercism.org/tracks/php/exercises',
          concepts: 'https://exercism.org/tracks/php/concepts',
        },
      },
      {
        slug: 'plsql',
        title: 'PL/SQL',
        course: false,
        num_concepts: 0,
        num_exercises: 11,
        web_url: 'https://exercism.org/tracks/plsql',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/plsql.svg',
        tags: [
          'Declarative',
          'Imperative',
          'Object-oriented',
          'Procedural',
          'Static',
          'Strong',
          'Compiled',
          'Interpreted',
          'Linux',
          'Language-specific runtime',
          'Backends',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/plsql',
          exercises: 'https://exercism.org/tracks/plsql/exercises',
          concepts: 'https://exercism.org/tracks/plsql/concepts',
        },
      },
      {
        slug: 'prolog',
        title: 'Prolog',
        course: false,
        num_concepts: 0,
        num_exercises: 19,
        web_url: 'https://exercism.org/tracks/prolog',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/prolog.svg',
        tags: [
          'Declarative',
          'Logic',
          'Dynamic',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Android',
          'Language-specific runtime',
          'Artificial Intelligence',
          'Backends',
          'Cross-platform development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/prolog',
          exercises: 'https://exercism.org/tracks/prolog/exercises',
          concepts: 'https://exercism.org/tracks/prolog/concepts',
        },
      },
      {
        slug: 'purescript',
        title: 'PureScript',
        course: false,
        num_concepts: 0,
        num_exercises: 28,
        web_url: 'https://exercism.org/tracks/purescript',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/purescript.svg',
        tags: [
          'Compiled',
          'Functional',
          'Linux',
          'Mac OSX',
          'Web Browser',
          'Windows',
          'Language-specific runtime',
          'Static',
          'Frontends',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/purescript',
          exercises: 'https://exercism.org/tracks/purescript/exercises',
          concepts: 'https://exercism.org/tracks/purescript/concepts',
        },
      },
      {
        slug: 'python',
        title: 'Python',
        course: true,
        num_concepts: 13,
        num_exercises: 131,
        web_url: 'https://exercism.org/tracks/python',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/python.svg',
        tags: [
          'Imperative',
          'Object-oriented',
          'Functional',
          'Dynamic',
          'Strong',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Artificial Intelligence',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Games',
          'Robotics',
          'Scientific calculations',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/python',
          exercises: 'https://exercism.org/tracks/python/exercises',
          concepts: 'https://exercism.org/tracks/python/concepts',
        },
      },
      {
        slug: 'r',
        title: 'R',
        course: false,
        num_concepts: 0,
        num_exercises: 35,
        web_url: 'https://exercism.org/tracks/r',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/r.svg',
        tags: [
          'Functional',
          'Object-oriented',
          'Dynamic',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Artificial Intelligence',
          'Scientific calculations',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/r',
          exercises: 'https://exercism.org/tracks/r/exercises',
          concepts: 'https://exercism.org/tracks/r/concepts',
        },
      },
      {
        slug: 'racket',
        title: 'Racket',
        course: false,
        num_concepts: 0,
        num_exercises: 33,
        web_url: 'https://exercism.org/tracks/racket',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/racket.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Dynamic',
          'Strong',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Backends',
          'GUIs',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/racket',
          exercises: 'https://exercism.org/tracks/racket/exercises',
          concepts: 'https://exercism.org/tracks/racket/concepts',
        },
      },
      {
        slug: 'raku',
        title: 'Raku',
        course: false,
        num_concepts: 0,
        num_exercises: 30,
        web_url: 'https://exercism.org/tracks/raku',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/raku.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Dynamic',
          'Weak',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Standalone executable',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/raku',
          exercises: 'https://exercism.org/tracks/raku/exercises',
          concepts: 'https://exercism.org/tracks/raku/concepts',
        },
      },
      {
        slug: 'reasonml',
        title: 'ReasonML',
        course: false,
        num_concepts: 0,
        num_exercises: 24,
        web_url: 'https://exercism.org/tracks/reasonml',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/reasonml.svg',
        tags: [
          'Functional',
          'Static',
          'Strong',
          'Compiled',
          'Linux',
          'Mac OSX',
          'Windows',
          'Web Browser',
          'Frontends',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/reasonml',
          exercises: 'https://exercism.org/tracks/reasonml/exercises',
          concepts: 'https://exercism.org/tracks/reasonml/concepts',
        },
      },
      {
        slug: 'ruby',
        title: 'Ruby',
        course: true,
        num_concepts: 16,
        num_exercises: 109,
        web_url: 'https://exercism.org/tracks/ruby',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/ruby.svg',
        tags: [
          'Functional',
          'Object-oriented',
          'Linux',
          'Windows',
          'Mac OSX',
          'Language-specific runtime',
          'Interpreted',
          'Dynamic',
          'Strong',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Games',
          'Robotics',
          'Scripts',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/ruby',
          exercises: 'https://exercism.org/tracks/ruby/exercises',
          concepts: 'https://exercism.org/tracks/ruby/concepts',
        },
      },
      {
        slug: 'rust',
        title: 'Rust',
        course: true,
        num_concepts: 12,
        num_exercises: 103,
        web_url: 'https://exercism.org/tracks/rust',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/rust.svg',
        tags: [
          'Functional',
          'Imperative',
          'Procedural',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Standalone executable',
          'Backends',
          'Cross-platform development',
          'Embedded systems',
          'Financial systems',
          'Frontends',
          'Games',
          'Robotics',
          'Scientific calculations',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/rust',
          exercises: 'https://exercism.org/tracks/rust/exercises',
          concepts: 'https://exercism.org/tracks/rust/concepts',
        },
      },
      {
        slug: 'scala',
        title: 'Scala',
        course: false,
        num_concepts: 0,
        num_exercises: 91,
        web_url: 'https://exercism.org/tracks/scala',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/scala.svg',
        tags: [
          'JVM (Java)',
          'Windows',
          'Linux',
          'Mac OSX',
          'Web Browser',
          'Imperative',
          'Functional',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Backends',
          'Frontends',
          'Financial systems',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/scala',
          exercises: 'https://exercism.org/tracks/scala/exercises',
          concepts: 'https://exercism.org/tracks/scala/concepts',
        },
      },
      {
        slug: 'scheme',
        title: 'Scheme',
        course: false,
        num_concepts: 0,
        num_exercises: 39,
        web_url: 'https://exercism.org/tracks/scheme',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/scheme.svg',
        tags: [
          'Functional',
          'Dynamic',
          'Strong',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/scheme',
          exercises: 'https://exercism.org/tracks/scheme/exercises',
          concepts: 'https://exercism.org/tracks/scheme/concepts',
        },
      },
      {
        slug: 'sml',
        title: 'Standard ML',
        course: false,
        num_concepts: 0,
        num_exercises: 27,
        web_url: 'https://exercism.org/tracks/sml',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/sml.svg',
        tags: [
          'Functional',
          'Imperative',
          'Static',
          'Strong',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Financial systems',
          'Scientific calculations',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/sml',
          exercises: 'https://exercism.org/tracks/sml/exercises',
          concepts: 'https://exercism.org/tracks/sml/concepts',
        },
      },
      {
        slug: 'swift',
        title: 'Swift',
        course: true,
        num_concepts: 41,
        num_exercises: 98,
        web_url: 'https://exercism.org/tracks/swift',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/swift.svg',
        tags: [
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Language-specific runtime',
          'Backends',
          'Frontends',
          'Mobile',
          'GUIs',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/swift',
          exercises: 'https://exercism.org/tracks/swift/exercises',
          concepts: 'https://exercism.org/tracks/swift/concepts',
        },
      },
      {
        slug: 'tcl',
        title: 'Tcl',
        course: false,
        num_concepts: 0,
        num_exercises: 121,
        web_url: 'https://exercism.org/tracks/tcl',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/tcl.svg',
        tags: [
          'Procedural',
          'Object-oriented',
          'Functional',
          'Imperative',
          'Dynamic',
          'Interpreted',
          'Windows',
          'Linux',
          'Mac OSX',
          'Cross-platform development',
          'Embedded systems',
          'GUIs',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/tcl',
          exercises: 'https://exercism.org/tracks/tcl/exercises',
          concepts: 'https://exercism.org/tracks/tcl/concepts',
        },
      },
      {
        slug: 'typescript',
        title: 'TypeScript',
        course: false,
        num_concepts: 0,
        num_exercises: 94,
        web_url: 'https://exercism.org/tracks/typescript',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/typescript.svg',
        tags: [
          'Declarative',
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Dynamic',
          'Strong',
          'Weak',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Language-specific runtime',
          'Artificial Intelligence',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Games',
          'GUIs',
          'Mobile',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/typescript',
          exercises: 'https://exercism.org/tracks/typescript/exercises',
          concepts: 'https://exercism.org/tracks/typescript/concepts',
        },
      },
      {
        slug: 'vbnet',
        title: 'VB.NET',
        course: false,
        num_concepts: 0,
        num_exercises: 20,
        web_url: 'https://exercism.org/tracks/vbnet',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/vbnet.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Static',
          'Strong',
          'Dynamic',
          'Weak',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'iOS',
          'Android',
          'Web Browser',
          'Common Language Runtime (.NET)',
          'Backends',
          'Cross-platform development',
          'Frontends',
          'Games',
          'GUIs',
          'Mobile',
          'Web development',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/vbnet',
          exercises: 'https://exercism.org/tracks/vbnet/exercises',
          concepts: 'https://exercism.org/tracks/vbnet/concepts',
        },
      },
      {
        slug: 'vimscript',
        title: 'Vim script',
        course: false,
        num_concepts: 0,
        num_exercises: 20,
        web_url: 'https://exercism.org/tracks/vimscript',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/vimscript.svg',
        tags: [
          'Functional',
          'Imperative',
          'Object-oriented',
          'Dynamic',
          'Weak',
          'Interpreted',
          'Windows',
          'Mac OSX',
          'Linux',
          'Language-specific runtime',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/vimscript',
          exercises: 'https://exercism.org/tracks/vimscript/exercises',
          concepts: 'https://exercism.org/tracks/vimscript/concepts',
        },
      },
      {
        slug: 'wren',
        title: 'Wren',
        course: false,
        num_concepts: 0,
        num_exercises: 53,
        web_url: 'https://exercism.org/tracks/wren',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/wren.svg',
        tags: [
          'Windows',
          'Linux',
          'Mac OSX',
          'Interpreted',
          'Object-oriented',
          'Standalone executable',
          'Games',
          'Scripts',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/wren',
          exercises: 'https://exercism.org/tracks/wren/exercises',
          concepts: 'https://exercism.org/tracks/wren/concepts',
        },
      },
      {
        slug: 'x86-64-assembly',
        title: 'x86-64 Assembly',
        course: false,
        num_concepts: 0,
        num_exercises: 17,
        web_url: 'https://exercism.org/tracks/x86-64-assembly',
        icon_url: 'https://dg8krxphbh767.cloudfront.net/tracks/x86-64-assembly.svg',
        tags: [
          'Imperative',
          'Procedural',
          'Static',
          'Weak',
          'Compiled',
          'Windows',
          'Mac OSX',
          'Linux',
          'Standalone executable',
          'Embedded systems',
        ],
        last_touched_at: null,
        is_new: true,
        links: {
          self: 'https://exercism.org/tracks/x86-64-assembly',
          exercises: 'https://exercism.org/tracks/x86-64-assembly/exercises',
          concepts: 'https://exercism.org/tracks/x86-64-assembly/concepts',
        },
      },
    ],
  };
  useEffect(() => {
    console.log(first);
  }, [first]);

  return (
    <div className=" rounded-lg drop-shadow-4xl w-[23.5rem] h-[22.75rem] section  bg-white overflow-y-auto overflow-x-hidden">
      <form>
        <div htmlFor="alltracks" className="flex my-2  items-center ">
          <input
            type="radio"
            name="tracks"
            id="alltracks"
            className="tracks ml-[1.5rem] absolute  z-10"
            onChange={() => setfirst('alltracks')}
            defaultChecked
          />
          <div className="mx-auto pl-[1.8rem] flex w-[22.5rem] h-[3.625rem] items-center justify-between">
            <div className="flex items-center ">
              <AllTracks className="ml-4 " />
              <span className="ml-4">All</span>
            </div>
            <h1 className=" px-4 py-2 border-1 rounded-full mr-4">9</h1>
          </div>
        </div>

        {tacks &&
          tacks.tracks.map((data, index) => (
            <Tracks key={index} setfirst={setfirst} id={index} data={data} />
          ))}
      </form>
    </div>
  );
}
